theme: null
minimal_mistakes_skin: "dark-skin"

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed


locale: "en-CA"
title: "Arya's Coding World"
description: "Welcome to my personal website, built with Jekyll and the Minimal Mistakes theme. This site is a hub for my micro:bit projects, coding experiments, and creative tech adventures."
title_separator: "-"
url: "https://microbitcoder652.github.io"
repository: "microbitcoder652/microbitcoder652.github.io"
words_per_minute: 200

masthead:
  enable: true

main:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "About Me"
    url: /about/
  - title: "GitHub"
    url: https://github.com/microbitcoder652

ui_text:
  en: &DEFAULT_EN
    breadcrumb_home_label      : "Home"
    breadcrumb_separator       : "/"
    follow_label               : "Links:"
    website_label              : "Website"
    email_label                : "Email"

comments:
  provider: "giscus"
    
google_site_verification : "MAWwgasCw3Iml0Db8EuyKc6cow_bU-wwvLxVtReG9fU"
bing_site_verification   : "1E8140AF75C7076B73F616579B8B2D76"

author:
  name             : "Arya Sharma"
  bio              : "I love coding and playing games"
  location         : "Scarborough, ON"
  email            : "arya.sharma2421@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-square-envelope"
      url: "mailto:arya.sharma2421@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/microbitcoder652"

footer:
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:arya.sharma2421@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/microbitcoder652"

